apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
spec:
  selector:
    app: nginx-lukas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30070
  type: NodePort 
